hros1/neck_controller:
  type: "effort_controllers/JointTrajectoryController"
  joints:
      - neck_yaw_powered_joint
      - neck_pitch_main_powered_joint
      
  gains:
    neck_yaw_powered_joint: {p: 100, d: 10, i: 0.1, i_clamp: 1}
    neck_pitch_main_powered_joint: {p: 100, d: 10, i: 0.1, i_clamp: 1}
            
hros1/left_arm_controller:
  type: "effort_controllers/JointTrajectoryController"
  joints:
    - left_shoulder_pitch_powered_joint
    - left_shoulder_roll_powered_joint
    - left_elbow_powered_joint
  gains:
    left_shoulder_pitch_powered_joint: {p: 100, d: 10, i: 0.1, i_clamp: 1}
    left_shoulder_roll_powered_joint: {p: 100, d: 10, i: 0.1, i_clamp: 1}
    left_elbow_powered_joint: {p: 100, d: 10, i: 0.1, i_clamp: 1}
   
hros1/right_arm_controller:
  type: "effort_controllers/JointTrajectoryController"
  joints:     
    - right_shoulder_pitch_powered_joint
    - right_shoulder_roll_powered_joint
    - right_elbow_powered_joint
  gains:
    right_shoulder_pitch_powered_joint: {p: 100, d: 10, i: 0.1, i_clamp: 1}
    right_shoulder_roll_powered_joint: {p: 100, d: 10, i: 0.1, i_clamp: 1}
    right_elbow_powered_joint: {p: 100, d: 10, i: 0.1, i_clamp: 1}        
        
hros1/left_leg_controller:
  type: "effort_controllers/JointTrajectoryController"
  joints:    
    - left_hip_yaw_powered_joint
    - left_hip_roll_powered_joint
    - left_hip_pitch_powered_joint
    - left_knee_pitch_powered_joint
    - left_ankle_pitch_powered_joint
    - left_ankle_roll_powered_joint
  gains:
    left_hip_yaw_powered_joint: {p: 100, d: 10, i: 0.1, i_clamp: 1}
    left_hip_roll_powered_joint: {p: 100, d: 10, i: 0.1, i_clamp: 1}
    left_hip_pitch_powered_joint: {p: 100, d: 10, i: 0.1, i_clamp: 1}
    left_knee_pitch_powered_joint: {p: 100, d: 10, i: 0.1, i_clamp: 1}
    left_ankle_pitch_powered_joint: {p: 100, d: 10, i: 0.1, i_clamp: 1}
    left_ankle_roll_powered_joint: {p: 100, d: 10, i: 0.1, i_clamp: 1}
        
        
hros1/right_leg_controller:
  type: "effort_controllers/JointTrajectoryController"
  joints:     
    - right_hip_yaw_powered_joint
    - right_hip_roll_powered_joint
    - right_hip_pitch_powered_joint
    - right_knee_pitch_powered_joint
    - right_ankle_pitch_powered_joint
    - right_ankle_roll_powered_joint
  gains:
    right_hip_yaw_powered_joint: {p: 100, d: 10, i: 0.1, i_clamp: 1}
    right_hip_roll_powered_joint: {p: 100, d: 10, i: 0.1, i_clamp: 1}
    right_hip_pitch_powered_joint: {p: 100, d: 10, i: 0.1, i_clamp: 1}
    right_knee_pitch_powered_joint: {p: 100, d: 10, i: 0.1, i_clamp: 1}
    right_ankle_pitch_powered_joint: {p: 100, d: 10, i: 0.1, i_clamp: 1}
    right_ankle_roll_powered_joint: {p: 100, d: 10, i: 0.1, i_clamp: 1}
