hros1:
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50
        
        
    neck_yaw_position_controller:
        type: effort_controllers/JointPositionController
        joint: neck_yaw_powered_joint
        pid: {p: 0.01, d: 0.0, i: 0}    
    neck_pitch_position_controller:
        type: effort_controllers/JointPositionController
        joint: neck_pitch_main_powered_joint
        pid: {p: 0.01, d: 0.0, i: 0}
        
    
        
    left_shoulder_pitch_position_controller:
        type: effort_controllers/JointPositionController
        joint: left_shoulder_pitch_powered_joint
        pid: {p: 0.01, d: 0.0, i: 0}
        
    left_shoulder_roll_position_controller:
        type: effort_controllers/JointPositionController
        joint: left_shoulder_roll_powered_joint
        pid: {p: 0.01, d: 0.0, i: 0}
        
    left_elbow_position_controller:
        type: effort_controllers/JointPositionController
        joint: left_elbow_powered_joint
        pid: {p: 0.001, d: 0.0, i: 0}
        
    
        
    right_shoulder_pitch_position_controller:
        type: effort_controllers/JointPositionController
        joint: right_shoulder_pitch_powered_joint
        pid: {p: 0.01, d: 0.0, i: 0}
        
    right_shoulder_roll_position_controller:
        type: effort_controllers/JointPositionController
        joint: right_shoulder_roll_powered_joint
        pid: {p: 0.01, d: 0.0, i: 0}
        
    right_elbow_position_controller:
        type: effort_controllers/JointPositionController
        joint: right_elbow_powered_joint
        pid: {p: 0.001, d: 0.0, i: 0}
        
     
        
    left_hip_yaw_position_controller:
        type: effort_controllers/JointPositionController
        joint: left_hip_yaw_powered_joint
        pid: {p: 0.01, d: 0.0, i: 0}
        
    left_hip_roll_position_controller:
        type: effort_controllers/JointPositionController
        joint: left_hip_roll_powered_joint
        pid: {p: 0.01, d: 0.0, i: 0}   
        
    left_hip_pitch_position_controller:
        type: effort_controllers/JointPositionController
        joint: left_hip_pitch_powered_joint
        pid: {p: 0.01, d: 0.0, i: 0}
        
    left_knee_pitch_position_controller:
        type: effort_controllers/JointPositionController
        joint: left_knee_pitch_powered_joint
        pid: {p: 0.01, d: 0.0, i: 0}
        
    left_ankle_pitch_position_controller:
        type: effort_controllers/JointPositionController
        joint: left_ankle_pitch_powered_joint
        pid: {p: 0.01, d: 0.0, i: 0}
        
    left_ankle_roll_position_controller:
        type: effort_controllers/JointPositionController
        joint: left_ankle_roll_powered_joint
        pid: {p: 0.01, d: 0.0, i: 0}
        
        
        
    right_hip_yaw_position_controller:
        type: effort_controllers/JointPositionController
        joint: right_hip_yaw_powered_joint
        pid: {p: 0.01, d: 0.0, i: 0}
        
    right_hip_roll_position_controller:
        type: effort_controllers/JointPositionController
        joint: right_hip_roll_powered_joint
        pid: {p: 0.01, d: 0.0, i: 0}   
        
    right_hip_pitch_position_controller:
        type: effort_controllers/JointPositionController
        joint: right_hip_pitch_powered_joint
        pid: {p: 0.01, d: 0.0, i: 0}
        
    right_knee_pitch_position_controller:
        type: effort_controllers/JointPositionController
        joint: right_knee_pitch_powered_joint
        pid: {p: 0.01, d: 0.0, i: 0}
        
    right_ankle_pitch_position_controller:
        type: effort_controllers/JointPositionController
        joint: right_ankle_pitch_powered_joint
        pid: {p: 0.01, d: 0.0, i: 0}
        
    right_ankle_roll_position_controller:
        type: effort_controllers/JointPositionController
        joint: right_ankle_roll_powered_joint
        pid: {p: 0.01, d: 0.0, i: 0} 
